spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/auth/**
        - id: ChatService
          uri: lb://ChatService
          predicates:
            - Path=/api/chat/**
        - id: MessageService
          uri: lb://MessageService
          predicates:
            - Path=/api/message/**
      default-filters:
        - name: JwtFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:8761/eureka/}